### ISSUE TITLE
request scope?

### ISSUE THREAD

**Issue by a5hpip3** [omniauth/omniauth-uber#3]
Hi,

I really like your gem for uber. There isn't a really clean way of getting uber authorization/token in rails and I'm working on a project that uses Uber. I've been able to get authorization and everything, but I'm stuck at the last step - making a request. The scope is currently invalid when added to the builder - I was wondering if you had any updates on this and were able to get the request scope going? If not, do you have any ideas as to how I could implement a request for ride in Rails? 

Thanks again!

**Comment by gabriel-dehan** [comment]
@a5hpip3 I know it is a bit late but I am going to add a pull requests that fixes it. For other people in need, all you have to do is to separate your scopes not with comma but with spaces.

`scope: 'profile request history'`

Cheers.

**Comment by tmilewski** [comment]
Closed per PR #4.
